- name: "{{ 'create /home/pi/RetroPie/roms/' + dest_dir }}"
  file:
    path: "{{ root_mount_point + '/home/pi/RetroPie/roms/' + dest_dir }}"
    state: directory

- name: copy roms
  ansible.builtin.copy:
    src: "{{ src_dir + '/' + item }}"
    dest: "{{ root_mount_point + '/home/pi/RetroPie/roms/' + dest_dir + '/' + item }}"
  loop: "{{roms}}"
